blank_issues_enabled: false
contact_links:
  - name: Security report
    url: https://github.com/springboardmentor425/B-13-SafetyEye-AI-Powered-Workplace-Occupancy-Safety-Monitor/security/advisories/new
    about: Report sensitive vulnerabilities privately.
